[package]
name = "fizika"
version = "0.1.0"
edition = "2021"
default-run = "fizika"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
headless_chrome = "0.9.0"
itertools = "0.10.3"
scraper = "0.13.0"
select = "0.5.0"
serde = "1.0.144"
serde_json = "1.0.85"
tendril = "0.4.3"
url = "2.2.2"
