import Head from 'next/head'
import { Inter } from 'next/font/google'
import { GetServerSideProps } from 'next'
import useSWR from 'swr'
import { Data } from './api/hello'

const inter = Inter({ subsets: ['latin'] })

/* export const getServerSideProps: GetServerSideProps = async (context) => {
  return { props: {} }
}*/

const fetcher = () => fetch("/api/hello").then((res) => res.json() as Promise<Data>)

export default function Home() {
  const { data, error } = useSWR('/api/profile-data', fetcher)

  if (error) return <div>Failed to load</div>
  if (!data) return <div>Loading...</div>

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {data.name}
      </main>
    </>
  )
}
